# Description: How many distinct terms are in the sequence generated by a^b for 2<=a<=100 and 2<=b<=100?

import math
import numpy as np
from utils.ntheory import *

def solve(n):
    s = 0
    pows = [
        [a**b for b in range(2, n+1)] for a in range(2, n+1)
    ]
    s = len(set([k for subpows in pows for k in subpows]))
    return s

if __name__ == "__main__":
    n = 100
    solution = solve(n)
    print(solution)